Gtad generating. BaseJob.
quotient-im/PyQuotient pull request #15
Opened 2021-07-07 04:44 UTC by Aksem

2021-07-09 14:34 UTC, KitsuneRal requested changes
Thanks, the direction looks quite sensible; some feedback on the current state below.

2021-07-12 06:40 UTC, KitsuneRal reviewed
Looks much better! A couple of suggestions from me.

2021-07-12 06:40 UTC, KitsuneRal commented on gtad/typesystem.xml.mustache
> +    </object-type>
Haven't tried but that should collapse empty XML elements to make generated files a bit less verbose:
```suggestion
    <object-type name="{{camelCaseOperationId}}Job"{{^models}} />{{/models}}{{#models}}>
      <!-- Inner data structures -->
        {{#model}}
      <value-type name="{{name}}" />
        {{/model}}
    </object-type>
      {{/models}}
```

2021-07-12 06:40 UTC, KitsuneRal commented on tools/patch_gtag_config.py
>      )
You already supply your modified copy of the GTAD config file in the source tree - is this copy-and-patch still needed? If you're concerned about the original file getting updates - I'll make sure to let you know and provide the update to your configuration "fork" as well.

2021-07-12 08:42 UTC, Aksem commented on tools/patch_gtag_config.py
>      )
Yes, the idea was to be able to update configuration when it's changed in libQuotient. And committed config was only to make sure that we have working version. But if you prefer to keep config and update it manually when needed - no problem, let's do so.

2021-07-12 08:49 UTC, Aksem commented on gtad/typesystem.xml.mustache
> +    </object-type>
Yes, it works as expected. Thanks!

2021-07-12 08:58 UTC, Aksem commented on PyQuotient/event-schemas/schema/m.room.member.xml
> +</typesystem>
Last version of GTAD configuration doesn't generate this file anymore.

2021-07-15 12:32 UTC, KitsuneRal commented on tools/patch_gtag_config.py
>      )
The thing is - you actually don't have that extensive `gtad.yaml` for your needs, you only use a smaller subset of it (especially when it comes to the Mustache partials library). So yes, let's maintain them separately, at least for now.

2021-07-15 13:00 UTC, KitsuneRal reviewed
Ok, I see a lot of progress - great job - but we have to cut this PR somewhere because it starts spinning out of control. It was originally aimed at getting the jobs working, and I totally get that `Connection` might be useful for that; but `Room` should really be spared for another PR. At this point it's worth spending a bit more effort at making the CI working.

2021-07-16 13:43 UTC, Aksem commented on tests/jobs/test_basejob.py
> +    #     assert isinstance(base_job, Quotient.BaseJob)
Unfortunately no, even after removing BaseJob::Query it doesn't work. Opened issue https://github.com/quotient-im/PyQuotient/issues/18 .

2021-07-16 13:45 UTC, Aksem commented on tests/jobs/test_basejob.py
> +    #     assert base_job.error == 404
Opened https://github.com/quotient-im/PyQuotient/issues/19

2021-07-16 15:34 UTC, KitsuneRal approved these changes
Awesome, CI is working - if you wish you can move the `Room` bindings out but since it's not the final PR anyway, it even is ok to keep it.

2021-07-16 15:45 UTC, merged